### ISSUE TITLE
negative epoc time/

### ISSUE THREAD

**Issue by hire-vladimir** [hire-vladimir/SA-quandl#5]
search for WIKI/IBM, noted that negative epoc time in _time is returned. why?

**Comment by metasyn** [comment]
<img width="1246" alt="screen shot 2015-09-24 at 10 37 33 am" src="https://cloud.githubusercontent.com/assets/1719730/10081139/4e9e5512-62a8-11e5-88e0-56d7914cd571.png">
looks pretty normal to me ?

**Comment by hire-vladimir** [comment]
@metasyn its actually an issue with epoc time, since it begins in 1970..

![screen shot 2015-09-24 at 3 03 39 pm](https://cloud.githubusercontent.com/assets/8716177/10088164/9e1bf962-62cd-11e5-8976-eae3fe3b4896.png)

**Comment by metasyn** [comment]
I know you closed this, but how'd you fix it ?

**Comment by hire-vladimir** [comment]
i can't fix it, splunk's _time is epoc based; there was no epoc prior 1970. you can still work with the data, just have to treat the Date column as string

**Comment by hire-vladimir** [comment]
When this scenario occurs, the command should show a visible warning to the user

**Comment by hire-vladimir** [comment]
test query

```
| quandl WIKI/IBM start_date=1969-12-31" end_date="1970-01-05" | table _time, Date
```

![screen shot 2015-12-21 at 6 22 53 pm](https://cloud.githubusercontent.com/assets/8716177/11946458/e56f8ec8-a80f-11e5-855c-4f494457697e.png)
