### ISSUE TITLE
Exception for long query

### ISSUE THREAD

**Issue by anthonygtellez** [hire-vladimir/SA-quandl#7]
No info on why this query failed. I assume it is because one of the codes failed. I pulled the codes directly from the world bank's documentation. I thought my last pull request debugged this issue, to tell you which code failed?

https://www.quandl.com/data/WCSC/documentation/metadata
<img width="1290" alt="screen shot 2016-02-03 at 1 36 19 am" src="https://cloud.githubusercontent.com/assets/8010133/12776929/cf859188-ca16-11e5-856e-2245846e07b2.png">

**Comment by anthonygtellez** [comment]
Seems to be a connection issue (hotel public wifi). Same query later yielded the following log, doesn't seem to be a consistent with failed network connectivity. 
`2016-02-03 03:53:33,291 ERROR  quandl[8108]:199 - error while processing events, exception="<urlopen error [Errno 113] No route to host>"`

**Comment by hire-vladimir** [comment]
@anthonygtellez that exception does indeed represent network issue, for what its worth i can also replicate the exception by disconnecting network connectivity on my development VM. I am closing the issue; can be re-opened in the future as needed. let me know.
